### ISSUE TITLE
Ghost tile doesn't work on Ubuntu default terminal.

### ISSUE THREAD

**Issue by JacobJustice** [k-vernooy/tetris#1]
I believe there should be a ghost tetrimino at the bottom of the screen but It doesn't show up for me on Ubuntu 18.04. I've tried it on gnome terminal and xterm and it doesn't work in either.

**Comment by k-vernooy** [comment]
The ghost tile will only appear if you use the command line option `--easy` or press `e` during the game. Are you doing either of these things?

**Comment by JacobJustice** [comment]
I was not, thanks!
