### ISSUE TITLE
Problem visualizing special characters on my customed project

### ISSUE THREAD

**Issue by josemarial16** [k-vernooy/tetris#7]
Hi, I am trying to add a network protocol in your code in order to control it remotely. I configured this using cmake and cmakelist to add all the libraries which i need. But, when it compiled and everything was looking good, it didnt show special characters correctly represented.  Thanks from a desperate student!

![InkedWhatsApp Image 2022-05-09 at 7 12 52 PM_LI](https://user-images.githubusercontent.com/48442630/167619142-1aa9e09e-284f-4550-ac15-dcadc67f79ca.jpg)

**Comment by k-vernooy** [comment]
Excited someone's working on this, sorry for the late response! If I recall correctly, this issue is because you're linking against the library `ncurses` instead of `ncursesw`. It has been a while since I last looked at this project, though, so please let me know if that's not the issue!

**Comment by josemarial16** [comment]
> 

Hi k-vernooy! Yes, the problem was the library that I needed to use so it get solved when I added  "-lncursesw" in the target libraries of the CMakeFile.txt. Thanks for your answer, tetris is looking so good now and I achieved to control it with a tactile internet protocol !

**Comment by k-vernooy** [comment]
Glad to hear it!

**Comment by DUOLabs333** [comment]
I have the same problem, but I have ncursesw installed.
